import { Finding, ScanResult, Severity } from '../models/scanResult';

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low', 'informational'];

/**
 * Generates report content in HTML, JSON, or Markdown formats
 * (PDF 2, FR-06). Every function here is a pure string transformation
 * with no file I/O - callers decide where the result gets written.
 *
 * Note on FR-06's "Reports contain no raw secrets" acceptance
 * criterion: this is satisfied structurally, not by redaction. The
 * Finding schema (see models/scanResult.ts, mirroring the engine's
 * Finding model) never stores the actual matched secret text - only
 * rule metadata, file, and line/column. There is nothing sensitive to
 * strip because nothing sensitive was ever captured.
 */
export class ReportGenerator {
  public static toJson(result: ScanResult): string {
    return JSON.stringify(result, null, 2);
  }

  public static toMarkdown(result: ScanResult): string {
    const lines: string[] = [];

    lines.push('# SentriCodeX Security Report');
    lines.push('');
    lines.push(`**Target:** \`${result.target}\``);
    lines.push(`**Scanned at:** ${result.scanned_at}`);
    lines.push(`**Files scanned:** ${result.files_scanned}`);
    lines.push(`**Duration:** ${result.duration_ms}ms`);
    lines.push(`**Security Score:** ${result.security_score}/100`);
    lines.push('');

    lines.push('## Summary');
    lines.push('');
    lines.push('| Severity | Count |');
    lines.push('|---|---|');
    for (const severity of SEVERITY_ORDER) {
      lines.push(
        `| ${capitalize(severity)} | ${result.summary.severity_breakdown[severity] ?? 0} |`
      );
    }
    lines.push('');

    lines.push('## Findings');
    lines.push('');

    if (result.findings.length === 0) {
      lines.push('No findings. Great work!');
    } else {
      lines.push('| Severity | Rule ID | File | Line | Description | Recommendation |');
      lines.push('|---|---|---|---|---|---|');
      for (const finding of sortBySeverity(result.findings)) {
        lines.push(
          `| ${capitalize(finding.severity)} | ${finding.rule_id} | ` +
            `${escapeMarkdownCell(finding.file)} | ${finding.line} | ` +
            `${escapeMarkdownCell(finding.description)} | ` +
            `${escapeMarkdownCell(finding.recommendation)} |`
        );
      }
    }
    lines.push('');
    lines.push('---');
    lines.push('_Generated by SentriCodeX - local-first static security analysis._');

    return lines.join('\n');
  }

  public static toHtml(result: ScanResult): string {
    const rows =
      result.findings.length === 0
        ? '<tr><td colspan="6" class="empty">No findings. Great work!</td></tr>'
        : sortBySeverity(result.findings)
            .map(
              (finding) => `<tr>
        <td><span class="badge badge-${finding.severity}">${finding.severity}</span></td>
        <td>${escapeHtml(finding.rule_id)}</td>
        <td>${escapeHtml(finding.file)}</td>
        <td>${finding.line}</td>
        <td>${escapeHtml(finding.description)}</td>
        <td>${escapeHtml(finding.recommendation)}</td>
      </tr>`
            )
            .join('\n');

    const summaryCards = SEVERITY_ORDER.map(
      (severity) => `<div class="card card-${severity}">
        <div class="count">${result.summary.severity_breakdown[severity] ?? 0}</div>
        <div class="label">${capitalize(severity)}</div>
      </div>`
    ).join('\n');

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>SentriCodeX Security Report</title>
<style>
  body { font-family: -apple-system, Segoe UI, sans-serif; margin: 0; padding: 32px; background: #1e1e1e; color: #ddd; }
  h1 { margin-bottom: 4px; }
  .meta { color: #999; font-size: 13px; margin-bottom: 24px; }
  .score { font-size: 40px; font-weight: 700; }
  .cards { display: grid; grid-template-columns: repeat(5, 1fr); gap: 10px; margin: 24px 0; }
  .card { border: 1px solid #444; border-left: 4px solid #888; border-radius: 4px; padding: 10px 14px; }
  .card-critical { border-left-color: #e51400; }
  .card-high { border-left-color: #f14c4c; }
  .card-medium { border-left-color: #e9a700; }
  .card-low { border-left-color: #3794ff; }
  .card-informational { border-left-color: #8a8a8a; }
  .card .count { font-size: 22px; font-weight: 700; }
  .card .label { font-size: 11px; color: #999; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }
  th, td { text-align: left; padding: 8px; border-bottom: 1px solid #333; }
  th { color: #999; text-transform: uppercase; font-size: 11px; }
  .badge { padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 600; color: #fff; text-transform: capitalize; }
  .badge-critical { background: #e51400; }
  .badge-high { background: #f14c4c; }
  .badge-medium { background: #e9a700; }
  .badge-low { background: #3794ff; }
  .badge-informational { background: #8a8a8a; }
  .empty { text-align: center; padding: 24px; color: #999; }
  footer { margin-top: 32px; color: #666; font-size: 12px; }
</style>
</head>
<body>
  <h1>SentriCodeX Security Report</h1>
  <p class="meta">
    <strong>${escapeHtml(result.target)}</strong><br/>
    Scanned ${result.scanned_at} &middot; ${result.files_scanned} file(s) &middot; ${result.duration_ms}ms
  </p>
  <div class="score">Security Score: ${result.security_score}/100</div>
  <div class="cards">
    ${summaryCards}
  </div>
  <table>
    <thead>
      <tr><th>Severity</th><th>Rule ID</th><th>File</th><th>Line</th><th>Description</th><th>Recommendation</th></tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>
  <footer>Generated by SentriCodeX &mdash; local-first static security analysis.</footer>
</body>
</html>`;
  }
}

function sortBySeverity(findings: Finding[]): Finding[] {
  const rank = Object.fromEntries(SEVERITY_ORDER.map((s, i) => [s, i]));
  return [...findings].sort((a, b) => rank[a.severity] - rank[b.severity]);
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function escapeMarkdownCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
