import { Finding, ScanResult, Severity, SuppressedFinding } from '../models/scanResult';

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low', 'informational'];

export class ReportGenerator {
  public static toJson(result: ScanResult): string { return JSON.stringify(result, null, 2); }

  public static toMarkdown(result: ScanResult): string {
    const lines: string[] = [];
    lines.push('# SentriCodeX Security Report', '');
    lines.push(`**Target:** \`${result.target}\``);
    lines.push(`**Scanned at:** ${result.scanned_at}`);
    lines.push(`**Files scanned:** ${result.files_scanned}`);
    lines.push(`**Duration:** ${result.duration_ms}ms`);
    lines.push(`**Security Score:** ${result.security_score}/100`, '');
    lines.push('## Summary', '', '| Metric | Count |', '|---|---|', `| Active Findings | ${result.findings.length} |`, `| Suppressed Findings | ${result.suppressed_findings.length} |`, `| Total Detected | ${result.findings.length + result.suppressed_findings.length} |`, '');
    lines.push('| Severity | Active Count |'); lines.push('|---|---|');
    for (const severity of SEVERITY_ORDER) lines.push(`| ${capitalize(severity)} | ${result.summary.severity_breakdown[severity] ?? 0} |`);
    lines.push('');
    lines.push('## Active Findings', '');
    if (!result.findings.length) lines.push(result.suppressed_findings.length ? 'No active findings.' : 'No findings. Great work!');
    else {
      lines.push('| Severity | Rule ID | File | Line | Description | Recommendation |','|---|---|---|---|---|---|');
      for (const f of sortBySeverity(result.findings)) lines.push(`| ${capitalize(f.severity)} | ${f.rule_id} | ${escapeMarkdownCell(f.file)} | ${f.line} | ${escapeMarkdownCell(f.description)} | ${escapeMarkdownCell(f.recommendation)} |`);
    }
    lines.push('', '## Suppressed Findings', '');
    if (!result.suppressed_findings.length) lines.push('No suppressed findings.');
    else {
      lines.push('| Severity | Rule ID | File | Line | Description | Suppression |','|---|---|---|---|---|---|');
      for (const f of result.suppressed_findings) lines.push(`| ${capitalize(f.severity)} | ${f.rule_id} | ${escapeMarkdownCell(f.file)} | ${f.line} | ${escapeMarkdownCell(f.description)} | ${escapeMarkdownCell(f.suppression_comment)} |`);
    }
    lines.push('', '---', '_Generated by SentriCodeX - local-first static security analysis._');
    return lines.join('\n');
  }

  public static toHtml(result: ScanResult): string {
    const activeRows = result.findings.length ? sortBySeverity(result.findings).map(renderFindingRow).join('\n') : `<tr><td colspan="6" class="empty">${result.suppressed_findings.length ? 'No active findings.' : 'No findings. Great work!'}</td></tr>`;
    const suppressedRows = result.suppressed_findings.length ? sortBySeverity(result.suppressed_findings).map(renderSuppressedRow).join('\n') : '<tr><td colspan="6" class="empty">No suppressed findings.</td></tr>';
    const summaryCards = SEVERITY_ORDER.map(s => `<div class="card card-${s}"><div class="count">${result.summary.severity_breakdown[s] ?? 0}</div><div class="label">${capitalize(s)}</div></div>`).join('');
    return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><title>SentriCodeX Security Report</title><style>
body{font-family:-apple-system,Segoe UI,sans-serif;margin:0;padding:32px;background:#1e1e1e;color:#ddd}h1{margin-bottom:4px}.meta{color:#999;font-size:13px;margin-bottom:24px}.score{font-size:40px;font-weight:700}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:24px 0}.card{border:1px solid #444;border-left:4px solid #888;border-radius:4px;padding:10px 14px}.card-critical{border-left-color:#e51400}.card-high{border-left-color:#f14c4c}.card-medium{border-left-color:#e9a700}.card-low{border-left-color:#3794ff}.card-informational{border-left-color:#8a8a8a}.card .count{font-size:22px;font-weight:700}.card .label{font-size:11px;color:#999}.summary-strip{display:flex;gap:12px;margin:18px 0 30px}.summary-pill{border:1px solid #444;border-radius:6px;padding:12px 16px}.summary-pill strong{display:block;font-size:20px}.summary-pill span{font-size:11px;color:#999}section{margin-top:30px}h2{font-size:18px}table{width:100%;border-collapse:collapse;margin-top:16px;font-size:13px}th,td{text-align:left;padding:8px;border-bottom:1px solid #333;vertical-align:top}th{color:#999;text-transform:uppercase;font-size:11px}.badge{padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600;color:#fff;text-transform:capitalize}.badge-critical{background:#e51400}.badge-high{background:#f14c4c}.badge-medium{background:#e9a700}.badge-low{background:#3794ff}.badge-informational{background:#8a8a8a}.suppressed-section{border-top:1px solid #444;padding-top:12px}.suppressed-row{opacity:.82}.suppression{font-family:monospace;font-size:12px;background:#2b2b2b;border-radius:4px;padding:4px 6px;display:inline-block}.empty{text-align:center;padding:24px;color:#999}footer{margin-top:32px;color:#666;font-size:12px}</style></head><body>
<h1>SentriCodeX Security Report</h1><p class="meta"><strong>${escapeHtml(result.target)}</strong><br/>Scanned ${result.scanned_at} &middot; ${result.files_scanned} file(s) &middot; ${result.duration_ms}ms</p><div class="score">Security Score: ${result.security_score}/100</div><div class="cards">${summaryCards}</div><div class="summary-strip"><div class="summary-pill"><strong>${result.findings.length}</strong><span>Active Findings</span></div><div class="summary-pill"><strong>${result.suppressed_findings.length}</strong><span>Suppressed Findings</span></div><div class="summary-pill"><strong>${result.findings.length + result.suppressed_findings.length}</strong><span>Total Detected</span></div></div>
<section><h2>Active Findings</h2><table><thead><tr><th>Severity</th><th>Rule ID</th><th>File</th><th>Line</th><th>Description</th><th>Recommendation</th></tr></thead><tbody>${activeRows}</tbody></table></section>
<section class="suppressed-section"><h2>Suppressed Findings (${result.suppressed_findings.length})</h2><p>These findings were detected but excluded from the active security results by an explicit SentriCodeX suppression comment.</p><table><thead><tr><th>Severity</th><th>Rule ID</th><th>File</th><th>Line</th><th>Description</th><th>Suppression</th></tr></thead><tbody>${suppressedRows}</tbody></table></section>
<footer>Generated by SentriCodeX &mdash; local-first static security analysis.</footer></body></html>`;
  }
}

function renderFindingRow(f: Finding): string { return `<tr><td><span class="badge badge-${f.severity}">${f.severity}</span></td><td>${escapeHtml(f.rule_id)}</td><td>${escapeHtml(f.file)}</td><td>${f.line}</td><td>${escapeHtml(f.description)}</td><td>${escapeHtml(f.recommendation)}</td></tr>`; }
function renderSuppressedRow(f: SuppressedFinding): string { return `<tr class="suppressed-row"><td><span class="badge badge-${f.severity}">${f.severity}</span></td><td>${escapeHtml(f.rule_id)}</td><td>${escapeHtml(f.file)}</td><td>${f.line}</td><td>${escapeHtml(f.description)}</td><td><span class="suppression">${escapeHtml(f.suppression_comment)}</span><br/><small>${escapeHtml(f.suppression_type)} suppression</small></td></tr>`; }
function sortBySeverity<T extends Finding>(findings: T[]): T[] { const rank = Object.fromEntries(SEVERITY_ORDER.map((s,i)=>[s,i])); return [...findings].sort((a,b)=>rank[a.severity]-rank[b.severity]); }
function capitalize(value:string):string{return value.charAt(0).toUpperCase()+value.slice(1)}
function escapeHtml(value:string):string{return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function escapeMarkdownCell(value:string):string{return value.replace(/\|/g,'\\|').replace(/\n/g,' ')}
